### ISSUE TITLE
Infinite Ore Box Shoveling

### ISSUE THREAD

**Issue by mastergandor** [Persistent-SS13/Persistent-SS13#1]
**Problem Description**:
You can shovel ore out of ore boxes infinitely.

**What did you expect to happen**: 
After shoveling the 2 ore I put in out, the box should have been empty.

**What happened instead**:
After shoveling the 2 ore I put in out, the box contained 2 ore still.

**Why is this bad/What are the consequences:**
Infinite Ore.

**Steps to reproduce the problem**:
1. Shovel ore into ore box.
2. Use shovel on ore box.
3. Repeat step 2.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: No.

**Comment by FaurnsGoldberg** [comment]
Fixed in latest revision, thanks for the report!
