### ISSUE TITLE
Captain's Quarters does not have power

### ISSUE THREAD

**Issue by XElectricX** [Persistent-SS13/Persistent-SS13#10]
**Problem Description**:
Every new shift, the APC does not supply power to the area.

**What did you expect to happen**: 
I thought it was because there was no power, but this happens every round, and the APC does have power.

**Why is this bad/What are the consequences:**
People can break in and steal the antique laser and spare ID by just using a crowbar.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
To return power to the room, the APC has to be reset.

**Comment by FaurnsGoldberg** [comment]
Fixed, all apcs reset correctly on map load now
