### ISSUE TITLE
Machines do not save their resources

### ISSUE THREAD

**Issue by XElectricX** [Persistent-SS13/Persistent-SS13#14]
**Problem Description**:
Protolathes, circuit imprinters, and exosuit fabricators do not save any materials put inside them.

**What did you expect to happen**: 
They SHOULD be keeping their resources when a new shift starts, but they do not.

**What happened instead**:
Every new shift, they are all empty.

**Why is this bad/What are the consequences:**
Results in lost resources when anyone forgets to empty the machines before a new round.

**Steps to reproduce the problem**:
Load a machine with materials, start a new round, look at the material menus. They are all empty.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Autolathe seems to be the only machine to keep its resources. However, circuit imprinter starts with 100 acid every round if you place 2 large beakers with acid inside it when building the circuit imprinter.

**Comment by FaurnsGoldberg** [comment]
This one is easy, just find every machine that holds materials and add 
map_storage_saved_vars = "density;icon_state;dir;name;pixel_x;pixel_y;req_access_txt;req_personal;materials" to it

**Comment by XElectricX** [comment]
Will do!
