### ISSUE TITLE
Can't call the shuttle

### ISSUE THREAD

**Issue by XElectricX** [Persistent-SS13/Persistent-SS13#15]
**Problem Description**:
Using the communications console to call the shuttle does not work. The game thinks you have not put a reason for calling the shuttle no matter what you type in.

**What did you expect to happen**: 
I tried making different combinations (1 letter, a full sentence with a period, gibberish, etc.) but none of them made any difference.

**What happened instead**:
The game keeps saying I need to put a reason for calling the shuttle.

**Why is this bad/What are the consequences:**
Can't change shifts until the crew vote, which happens every hour.

**Steps to reproduce the problem**:
Go to a communications console, swipe ID, call the shuttle, then receive the error. I tried it first as a Research Director and I thought I just did not have permission, then I tried it as Captain and the same thing happened.

**Comment by FaurnsGoldberg** [comment]
Cannot replicate, although you might have been putting too short a reason

**Comment by XElectricX** [comment]
Could that be it? I'll see if I can do it again.

**Comment by XElectricX** [comment]
Yep, needed to make the reason a lot longer to call the shuttle.
