### ISSUE TITLE
Floor Tile Reversion

### ISSUE THREAD

**Issue by jipowap** [Persistent-SS13/Persistent-SS13#16]
**Problem Description**:
Floor tiles in certain locales revert to original paint scheme

**What did you expect to happen**: 
Used floor painter to clean up Assembly Line and Gas Turbine flooring of their rustiness.

**What happened instead**:
Upon next shift all tiles reverted to their grimy old selves

**Why is this bad/What are the consequences:**
Even if an area is completely reworked, some tiles will not be changed.

**Steps to reproduce the problem**:
Floor painter in those two areas->Shift End->New Shift

**Possibly related stuff**:
Doesn't seem to affect any other tile type/area. Assembly line is a persistent locale, not sure about Gas Turbine.

**Comment by FaurnsGoldberg** [comment]
has anyone replicated this lately?
