### ISSUE TITLE
Faxes are broken

### ISSUE THREAD

**Issue by ben10083** [Persistent-SS13/Persistent-SS13#17]
**Problem Description**:
I You cannot fax paper

**What did you expect to happen**: 
I expected it to send paper to Head of Security office, so HoS can have paper.

**What happened instead**:
It said "error, cannot transmit message" every time I tried, and admins said it happens for all destinations including centcom.

**Why is this bad/What are the consequences:**
1. Prevents centcom faxes
2. Prevents faxes to other command staff

**Steps to reproduce the problem**:
log into a fax machine, insert paper, set destination to head of security's office, press send and get the error message.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
It may just not be able to locate fax machine.

**Comment by FaurnsGoldberg** [comment]
fixed
