### ISSUE TITLE
Petraspider Hole Collapse Icon Glitch

### ISSUE THREAD

**Issue by mastergandor** [Persistent-SS13/Persistent-SS13#2]
**Problem Description**:
When you collapse a petraspider hole with a pickaxe it still looks like there is a hole there even though it is gone.

**What did you expect to happen**: 
I expected the ground to not look like a hole anymore.

**What happened instead**:
The ground still looked like it had a hole.

**Why is this bad/What are the consequences:**
Confusing on which holes are still there and which have been collapsed.

**Steps to reproduce the problem**:
1. Pickaxe a petraspider hole.
2. Observe how it still looks like a hole is there.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: No.

**Comment by FaurnsGoldberg** [comment]
Fixed in latest revision

**Comment by FaurnsGoldberg** [comment]
Thanks for the report!
