### ISSUE TITLE
Indestructable Firelocks

### ISSUE THREAD

**Issue by jipowap** [Persistent-SS13/Persistent-SS13#20]
**Problem Description**:
Firelock type hatches can not be deconstructed. Even by RCD.

**What did you expect to happen**: 
I tried every tool to attempt to open electronics or similar maintenance function.

**What happened instead**:
I was given to 'do you wish to open/close' prompt.

**Why is this bad/What are the consequences:**
Should one wish to construct, or repair, an area it is sometimes necessary to remove them. Large scale explosions and gravity waves seem to move hatches and the likes frequently.

**Steps to reproduce the problem**:
Attempt to use anything upon the hatch, save welding.

**Possibly related stuff**: 
None that I can think of, but conveyor belts are in a similar, invincible, situation. It takes a singularity to remove them.

**Comment by XElectricX** [comment]
@jipowap Should close this.
