### ISSUE TITLE
Players are renamed when cloned or dead

### ISSUE THREAD

**Issue by XElectricX** [Persistent-SS13/Persistent-SS13#26]
**Problem Description**:
When you die or are cloned, you get a different name.

**Why is this bad/What are the consequences:**
Players permanently lose their names. More importantly, **any locks made by the player will not be unlockable due to them having a new name.**

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Strangely enough, the names given are not based on RNG. They are preset no matter how many times you die. For example: Bob will always come back as Tim when he is cloned, no matter what.

**Comment by FaurnsGoldberg** [comment]
hmm, this was fixed a while back but old characters still have the issue (their dna has a different name then the one they chose, so clones and brains have the wrong name, newer characters dont have this problem (from what i've tested). im not sure how to fix the older characters

**Comment by XElectricX** [comment]
Oh darn.
