### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by RobertRoberts2020** [Persistent-SS13/Persistent-SS13#74]
**Problem Description**:
The thing doesn't compile.

**What did you expect to happen**: 
I was expecting for the thing to compile.

**What happened instead**:
It didn't

**Why is this bad/What are the consequences:**
Because it doesn't compile

**Steps to reproduce the problem**:
Try to compile the thing, it doesn't compile.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 

loading paradise.dme
code\game\gamemodes\wizard\soulstone.dm:106:error: expected var or proc name after . operator
paradise.dmb - 1 error, 0 warnings (5/26/19 4:52 am)

EDIT 1 : oh god why aren't lines numbered?

EDIT2: Workaround:

https://i.postimg.cc/WzLrXwYZ/fixed-it.jpg

EDIT3: The workaround was a catastrophic failure.

**Comment by Andrew-Fall** [comment]
@RobertRoberts2020 Lol, this is discontinued code, I suppose we should have just deleted it
